### ISSUE TITLE
Modificar DB

### ISSUE THREAD

**Issue by Castolo10** [Castolo10/CiberQuizz-CUCEI-API#11]
Agregar tabla de tokens a la base de datos, agregar campo "exist" para preguntas y usuarios para realizar eliminaciones lógicas y cambiar permisos por roles(nombre del atributo) y agregar campo para la tabla de amigos para el status de la solicitud.

**Comment by Ngrajeda** [comment]
La base de datos ya fue actualizada, falta la tabla de tokens

**Comment by Castolo10** [comment]
Enterado!
